export enum TypeQuestionEnum {
  'QCM_COMPLETE_PHRASE_WITH_WORD' = 'QCM_COMPLETE_PHRASE_WITH_WORD',
  'QCM_COMPLETE_PHRASE_WITH_PHRASE' = 'QCM_COMPLETE_PHRASE_WITH_PHRASE',
  'QCM_CHOOSE_PHRASE' = 'QCM_CHOOSE_PHRASE',
  'QCM_CHOOSE_WORD' = 'QCM_CHOOSE_WORD',
  'QCM_OPTION' = 'QCM_OPTION',
  'QCM_DRAG_SMALL' = 'QCM_DRAG_SMALL',
  'QCM_DRAG_BIG' = 'QCM_DRAG_BIG',
  'QCM_MULTI_ANSWER_WORDS' = 'QCM_MULTI_ANSWER_WORDS',
  'QCM_MULTI_ANSWER_PHRASE_SMALL' = 'QCM_MULTI_ANSWER_PHRASE_SMALL',

  //----------------------------------------------------------------------------//

  'QCM_MULTI_ANSWER_IMAGES' = 'QCM_MULTI_ANSWER_IMAGES',
  'QCM_MULTI_ANSWER_WORDS_IMAGES' = 'QCM_MULTI_ANSWER_WORDS_IMAGES',
  'DRAG_DROP_IN_TABLE_IMAGES' = 'DRAG_DROP_IN_TABLE_IMAGES',
  'DRAG_DROP_WORDS_TO_IMAGE' = 'DRAG_DROP_WORDS_TO_IMAGE',
  'SELECT_TABLE' = 'SELECT_TABLE',
  'COLOR' = 'COLOR',
  'ARROW' = 'ARROW',
  'ARROW_SOUND' = 'ARROW_SOUND',
  'VIDEO' = 'VIDEO',
  'READ' = 'READ',
  'READ_IMAGE' = 'READ_IMAGE',
  'MAKE_PHRASE' = 'MAKE_PHRASE',
  'MAKE_PHRASE_FROM_TABLE' = 'MAKE_PHRASE_FROM_TABLE'
}

export enum TypeQuestionEnumCommun {
  'QCM_COMPLETE_PHRASE_WITH_WORD' = 'QCM_COMPLETE_PHRASE_WITH_WORD',
  'QCM_COMPLETE_PHRASE_WITH_PHRASE' = 'QCM_COMPLETE_PHRASE_WITH_PHRASE',
  'QCM_CHOOSE_PHRASE' = 'QCM_CHOOSE_PHRASE',
  'QCM_CHOOSE_WORD' = 'QCM_CHOOSE_WORD',
  'QCM_OPTION' = 'QCM_OPTION',
  'QCM_DRAG_SMALL' = 'QCM_DRAG_SMALL',
  'QCM_DRAG_BIG' = 'QCM_DRAG_BIG',
  'QCM_MULTI_ANSWER_WORDS' = 'QCM_MULTI_ANSWER_WORDS',
  'QCM_MULTI_ANSWER_PHRASE_SMALL' = 'QCM_MULTI_ANSWER_PHRASE_SMALL'
}
